/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfigResponse */
        ConfigResponse: {
            /** Rules Version */
            rules_version: string;
            /** Type Rules */
            type_rules: components["schemas"]["TypeRule"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            cost_weights: components["schemas"]["CostWeights"];
            /** Excluded Statuses */
            excluded_statuses: string[];
        };
        /** CostWeights */
        CostWeights: {
            /**
             * Year Gap
             * @default 1000
             */
            year_gap: number;
            /**
             * Location Mismatch
             * @default 100
             */
            location_mismatch: number;
            /**
             * Fifo Rank
             * @default 0.001
             */
            fifo_rank: number;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** Location */
        Location: {
            /** City */
            city: string;
            /** Building */
            building: string;
            /** Site Code */
            site_code: string;
        };
        /** TypeRule */
        TypeRule: {
            /** Item */
            item: string;
            /**
             * Keyword
             * @default
             */
            keyword: string;
            /** Sap Type */
            sap_type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
}
