/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description A new, empty session. Upload the original inventory next.
         */
        post: operations["create_session_api_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description Which steps are done: the uploads (with their summaries) and whether matching ran.
         */
        get: operations["get_state_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_api_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 1: upload the original inventory (read only, never modified)
         * @description Uploading again replaces the original inventory and discards the incoming list and
         *     every decision (the UI asks for confirmation first). A failed upload changes nothing.
         */
        post: operations["upload_original_api_sessions__session_id__original_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/incoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 2: upload the incoming furniture list
         * @description 409 until the original inventory is uploaded. Matching does not start yet: see
         *     ``POST /match``. Uploading again discards an earlier matching and its decisions.
         */
        post: operations["upload_incoming_api_sessions__session_id__incoming_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Step 3: start the matching
         * @description Runs the matching once both files are uploaded (409 before). Calling it again
         *     returns the existing result with its decisions.
         */
        post: operations["start_matching_api_sessions__session_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Result
         * @description Summary, the status of every incoming row, warnings, unpaired units, decision log.
         */
        get: operations["get_result_api_sessions__session_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/incoming/{row}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidates
         * @description Existing units for one incoming row, best first (a QR-code match always leads).
         */
        get: operations["get_candidates_api_sessions__session_id__incoming__row__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/incoming/{row}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Assignment
         * @description Pair the row with a unit, or mark it as having no pair (reason required).
         *
         *     If the unit belongs to another row the answer is 409 ``swap_required`` describing the
         *     swap; with ``confirm_swap`` that row is released back to the items to resolve.
         */
        put: operations["put_assignment_api_sessions__session_id__incoming__row__assignment_put"];
        post?: never;
        /**
         * Delete Assignment
         * @description Back to the automatic suggestion.
         */
        delete: operations["delete_assignment_api_sessions__session_id__incoming__row__assignment_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export
         * @description The incoming file as uploaded, with only its Asset ID cells written. 409 while any
         *     item is unresolved. The original inventory is never exported.
         */
        get: operations["export_api_sessions__session_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignmentRequest */
        AssignmentRequest: {
            /**
             * Asset Id
             * @description Asset ID from the original inventory; null = the item has no existing pair.
             */
            asset_id: string | null;
            /** @description Required when asset_id is null; 'other' also needs a note. */
            reason?: components["schemas"]["NoMatchReason"] | null;
            /** Note */
            note?: string | null;
            /**
             * Confirm Swap
             * @description Take the unit even if another row holds it (that row is released).
             * @default false
             */
            confirm_swap: boolean;
        };
        /** AssignmentResponse */
        AssignmentResponse: {
            /** Row */
            row: number;
            /**
             * Released Row
             * @description Row that lost its unit in a swap and is back among the items to resolve.
             */
            released_row: number | null;
            result: components["schemas"]["SessionResult"];
        };
        /** Body_upload_incoming_api_sessions__session_id__incoming_post */
        Body_upload_incoming_api_sessions__session_id__incoming_post: {
            /**
             * File
             * @description The incoming furniture list workbook
             */
            file: string;
            /**
             * Sheet
             * @description Sheet to read; needed if several fit
             */
            sheet?: string | null;
        };
        /** Body_upload_original_api_sessions__session_id__original_post */
        Body_upload_original_api_sessions__session_id__original_post: {
            /**
             * File
             * @description The original inventory workbook
             */
            file: string;
            /**
             * Sheet
             * @description Sheet to read; needed if several fit
             */
            sheet?: string | null;
        };
        /** Candidate */
        Candidate: {
            existing: components["schemas"]["ExistingItem"];
            /** Score */
            score: number;
            /** Checks */
            checks: components["schemas"]["CriterionCheck"][];
            /** Hard Ok */
            hard_ok: boolean;
            /** Qr Match */
            qr_match: boolean;
            /** Paired Row */
            paired_row: number | null;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Rules Version */
            rules_version: string;
            /** Type Rules */
            type_rules: components["schemas"]["TypeRule"][];
            /** Locations */
            locations: components["schemas"]["Location"][];
            scoring: components["schemas"]["ScoringConfig"];
            /** Excluded Statuses */
            excluded_statuses: string[];
        };
        /**
         * Criterion
         * @enum {string}
         */
        Criterion: "type" | "color" | "size" | "location" | "material";
        /** CriterionCheck */
        CriterionCheck: {
            criterion: components["schemas"]["Criterion"];
            /** Evaluable */
            evaluable: boolean;
            /** Match */
            match: boolean | null;
            /** Existing */
            existing: string | null;
            /** Incoming */
            incoming: string | null;
        };
        /** DuplicateRow */
        DuplicateRow: {
            /** Row */
            row: number;
            /** Duplicate Of */
            duplicate_of: number;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /**
             * Details
             * @default []
             */
            details: {
                [key: string]: unknown;
            }[];
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /**
         * ExistingItem
         * @description A unit of the original inventory (one per Asset ID).
         */
        ExistingItem: {
            /** Excel Row */
            excel_row: number;
            /** Asset Id */
            asset_id: string;
            /** Item Name */
            item_name: string | null;
            /** Description */
            description: string | null;
            /** Sap Type */
            sap_type: string | null;
            /** Color */
            color: string | null;
            /** Width Cm */
            width_cm: number | null;
            /** Size Word */
            size_word: string | null;
            /** Materials */
            materials: string[];
            /** City */
            city: string | null;
            /** Building */
            building: string | null;
            /** Custodian */
            custodian: string | null;
            /** Activation Date */
            activation_date: string | null;
            /** Deactivation Date */
            deactivation_date: string | null;
            /** Status */
            status: string | null;
            /** Defective */
            defective: boolean;
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** IncomingItem */
        IncomingItem: {
            /** Excel Row */
            excel_row: number;
            /** Asset Id */
            asset_id: string | null;
            /** Asset Group */
            asset_group: string | null;
            /** Asset Category */
            asset_category: string | null;
            /** Item Name */
            item_name: string | null;
            /** Color */
            color: string | null;
            /** Material */
            material: string | null;
            /** Width Cm */
            width_cm: number | null;
            /** Height Cm */
            height_cm: number | null;
            /** Depth Cm */
            depth_cm: number | null;
            /** Serial No */
            serial_no: string | null;
            /** Remarks */
            remarks: string | null;
            /** Qr Code */
            qr_code: string | null;
            /** Building */
            building: string | null;
            /** City */
            city: string | null;
            /** Duplicate Of */
            duplicate_of: number | null;
        };
        /** IncomingResult */
        IncomingResult: {
            item: components["schemas"]["IncomingItem"];
            status: components["schemas"]["RowStatus"];
            /** Resolved */
            resolved: boolean;
            /** Asset Id */
            asset_id: string | null;
            /** Existing Row */
            existing_row: number | null;
            /** Score */
            score: number | null;
            /** Checks */
            checks?: components["schemas"]["CriterionCheck"][];
            /**
             * Location Mismatch
             * @default false
             */
            location_mismatch: boolean;
            /**
             * Tie Resolved
             * @default false
             */
            tie_resolved: boolean;
            /** Auto Asset Id */
            auto_asset_id?: string | null;
            reason?: components["schemas"]["NoMatchReason"] | null;
            /** Note */
            note?: string | null;
            /** Notes */
            notes?: components["schemas"]["Note"][];
        };
        /** IncomingSummary */
        IncomingSummary: {
            /** Rows */
            rows: number;
            /** Locations */
            locations: components["schemas"]["LocationCount"][];
            /** Item Types */
            item_types: number;
            /** Duplicate Rows */
            duplicate_rows: components["schemas"]["DuplicateRow"][];
            /** Prefilled Asset Ids */
            prefilled_asset_ids: number[];
            /** Issues */
            issues: components["schemas"]["RowIssue"][];
        };
        /** IncomingUpload */
        IncomingUpload: {
            sheet: components["schemas"]["SheetInfo"];
            summary: components["schemas"]["IncomingSummary"];
        };
        /** IncomingUploaded */
        IncomingUploaded: {
            /** Session Id */
            session_id: string;
            incoming: components["schemas"]["IncomingUpload"];
            /**
             * Discarded Decisions
             * @description True if an earlier matching result (and its decisions) was discarded.
             */
            discarded_decisions: boolean;
        };
        /** Location */
        Location: {
            /** City */
            city: string;
            /** Building */
            building: string;
            /** Site Code */
            site_code: string;
        };
        /** LocationCount */
        LocationCount: {
            /** Location */
            location: string;
            /** Building */
            building: string | null;
            /** Rows */
            rows: number;
        };
        /**
         * LogAction
         * @enum {string}
         */
        LogAction: "assign" | "no_match" | "reset" | "released";
        /** LogEntry */
        LogEntry: {
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Row */
            row: number;
            action: components["schemas"]["LogAction"];
            /** Old Asset Id */
            old_asset_id: string | null;
            /** New Asset Id */
            new_asset_id: string | null;
            reason?: components["schemas"]["NoMatchReason"] | null;
            /** Note */
            note?: string | null;
        };
        /** MatchSummary */
        MatchSummary: {
            /** Incoming Rows */
            incoming_rows: number;
            /** Existing Units */
            existing_units: number;
            /** Resolved */
            resolved: number;
            /** Unresolved */
            unresolved: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Location Mismatches */
            location_mismatches: number;
            /** Tie Resolved */
            tie_resolved: number;
            /** Unpaired Existing */
            unpaired_existing: number;
            /** Auto Match Threshold */
            auto_match_threshold: number;
            /** Export Ready */
            export_ready: boolean;
        };
        /**
         * NoMatchReason
         * @enum {string}
         */
        NoMatchReason: "missing_asset" | "new_asset" | "duplicate_entry" | "other";
        /**
         * Note
         * @description One message: ``code`` + ``params`` for translation, ``text`` in English.
         */
        Note: {
            /** Code */
            code: string;
            /** Params */
            params?: {
                [key: string]: string | number | null;
            };
            /** Text */
            text: string;
        };
        /** OriginalSummary */
        OriginalSummary: {
            /** Rows */
            rows: number;
            /** Locations */
            locations: components["schemas"]["LocationCount"][];
            /** Duplicate Asset Ids */
            duplicate_asset_ids: components["schemas"]["RepeatedValue"][];
            /** Duplicate Rows */
            duplicate_rows: components["schemas"]["DuplicateRow"][];
            /** Defective Rows */
            defective_rows: number[];
            /** Issues */
            issues: components["schemas"]["RowIssue"][];
        };
        /** OriginalUpload */
        OriginalUpload: {
            sheet: components["schemas"]["SheetInfo"];
            summary: components["schemas"]["OriginalSummary"];
        };
        /** OriginalUploaded */
        OriginalUploaded: {
            /** Session Id */
            session_id: string;
            original: components["schemas"]["OriginalUpload"];
            /**
             * Discarded Later Steps
             * @description True if an incoming list (and its decisions) existed and was discarded.
             */
            discarded_later_steps: boolean;
        };
        /** RepeatedValue */
        RepeatedValue: {
            /** Value */
            value: string;
            /** Rows */
            rows: number[];
        };
        /** RowIssue */
        RowIssue: {
            /** Row */
            row: number | null;
            /** Code */
            code: string;
            /** Params */
            params?: {
                [key: string]: string | number | null;
            };
            /** Message */
            message: string;
        };
        /**
         * RowStatus
         * @description Status of one incoming row (section 4).
         * @enum {string}
         */
        RowStatus: "auto" | "auto_newest" | "location_mismatch" | "manual" | "no_match" | "no_candidate" | "duplicate";
        /**
         * ScoringConfig
         * @description Every criterion counts equally; only a full match is paired automatically.
         */
        ScoringConfig: {
            /**
             * Auto Match Threshold
             * @default 100
             */
            auto_match_threshold: number;
            /**
             * Material Keywords
             * @default []
             */
            material_keywords: string[];
            /**
             * Material Synonyms
             * @default {}
             */
            material_synonyms: {
                [key: string]: string[];
            };
        };
        /** SessionResult */
        SessionResult: {
            summary: components["schemas"]["MatchSummary"];
            /** Rows */
            rows: components["schemas"]["IncomingResult"][];
            /** Unpaired Existing */
            unpaired_existing: components["schemas"]["ExistingItem"][];
            /** Log */
            log: components["schemas"]["LogEntry"][];
            /** Warnings */
            warnings: components["schemas"]["Note"][];
            /** Session Id */
            session_id: string;
        };
        /**
         * SessionState
         * @description Where a session is in the upload → match flow.
         */
        SessionState: {
            /** Session Id */
            session_id: string;
            original: components["schemas"]["OriginalUpload"] | null;
            incoming: components["schemas"]["IncomingUpload"] | null;
            /** Matched */
            matched: boolean;
        };
        /** SheetInfo */
        SheetInfo: {
            /** File Name */
            file_name: string;
            /** Sheet Name */
            sheet_name: string;
            /**
             * Detected By
             * @enum {string}
             */
            detected_by: "sheet_name" | "header_signature" | "user_choice";
            /** Sheets Available */
            sheets_available: string[];
            /** Row Count */
            row_count: number;
            /** Missing Optional Columns */
            missing_optional_columns: string[];
        };
        /** TypeRule */
        TypeRule: {
            /** Item */
            item: string;
            /**
             * Keyword
             * @default
             */
            keyword: string;
            /** Sap Type */
            sap_type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    create_session_api_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
        };
    };
    get_state_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionState"];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_session_api_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_original_api_sessions__session_id__original_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_original_api_sessions__session_id__original_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OriginalUploaded"];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A previous step is not done yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_incoming_api_sessions__session_id__incoming_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_incoming_api_sessions__session_id__incoming_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncomingUploaded"];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A previous step is not done yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    start_matching_api_sessions__session_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A previous step is not done yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_result_api_sessions__session_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResult"];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A previous step is not done yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_candidates_api_sessions__session_id__incoming__row__candidates_get: {
        parameters: {
            query?: {
                /** @description Also units assigned to other rows */
                include_paired?: boolean;
                /** @description Also units of other types */
                include_other_types?: boolean;
                /** @description Also defective units */
                include_defective?: boolean;
                /** @description Search Asset ID, description, custodian */
                q?: string | null;
            };
            header?: never;
            path: {
                row: number;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"][];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description A previous step is not done yet */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_assignment_api_sessions__session_id__incoming__row__assignment_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row: number;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Matching has not run, or the unit belongs to another row (code swap_required: repeat with confirm_swap) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_assignment_api_sessions__session_id__incoming__row__assignment_delete: {
        parameters: {
            query?: {
                /** @description Take back the unit from another row */
                confirm_swap?: boolean;
            };
            header?: never;
            path: {
                row: number;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Matching has not run, or the unit belongs to another row (code swap_required: repeat with confirm_swap) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_api_sessions__session_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The uploaded incoming workbook with its Asset IDs filled in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": unknown;
                };
            };
            /** @description Unknown session or row */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Matching has not run, or items are still unresolved (code unresolved_items) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
